version: "3"
services:
    database:
        image: postgres
        ports:
            - 8082:5432
        environment:
            POSTGRES_PASSWORD: DB_PASSWORD
    item-storage:
        build: ./item-storage
        ports:
            - 8080:8080
        depends_on:
            - "database"
        command: ["./wait-for-it.sh", "database:5432", "--", "./item-storage"]
        environment:
            DATABASE_URL: "postgres://postgres:DB_PASSWORD@database:5432/postgres"
            AUTH_SERVER_ADDRESS: "http://auth:8080/validate"
    auth:
        build: ./authentication
        ports:
            - 8081:8080
        depends_on:
            - "database"
        command: ["./wait-for-it.sh", "database:5432", "--", "./authentication"]
        environment:
            DATABASE_URL: "postgres://postgres:DB_PASSWORD@database:5432/postgres"
            TOKEN_LENGTH: "10"
            REFRESH_TOKEN_LIFE_TIME: "24h"
            ACCESS_TOKEN_LIFE_TIME: "30m"
    rabbit-mq:
        image: rabbitmq:management
        ports:
            - 8083:15672
    notifier:
        build: ./notifier
        depends_on:
            - "rabbit-mq"
        command: ["./wait-for-it.sh", "rabbit-mq:5672", "--", "./notifier"]
        environment:
            EMAIL_PROVIDER_ADDRESS: "http://provider-mock:8080/send"
            PROVIDER_API_ID: "1234567890"
            MESSAGE_QUEUE_URL: "amqp://guest:guest@rabbit-mq:5672/"
    provider-mock:
        build: ./provider-mock
        command: ["./provider-mock"]