version: "3"
services:
    database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: DB_PASSWORD
    restful_api:
        build: .
        ports:
            - 8080:8080
        depends_on:
            - "database"
        command: ["./wait-for-it.sh", "database:5432", "--", "./main"]
        environment:
            DATABASE_URL: "postgres://postgres:DB_PASSWORD@database:5432/postgres"