FROM golang:latest AS builder
ARG service_name
ENV SERVICE_NAME=${service_name} 
WORKDIR /go/src/${SERVICE_NAME}/
COPY common ../common
COPY ${SERVICE_NAME}/go.mod .
COPY ${SERVICE_NAME}/go.sum .
RUN go mod download
COPY ${service_name}/ .
RUN go build -o /build/${SERVICE_NAME} .

FROM alpine:latest
RUN  apk update && apk add ca-certificates libc6-compat bash
WORKDIR /app/
COPY wait-for-it/wait-for-it.sh .
COPY --from=builder /build/${service_name} ./${service_name}
